# Generated by Django 4.1.7 on 2023-03-03 06:31

import client_review.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to=client_review.models.upload_to)),
                ('country_image', models.ImageField(blank=True, null=True, upload_to=client_review.models.upload_to)),
                ('review_content', models.TextField()),
            ],
        ),
    ]
