# Generated by Django 4.1.7 on 2023-03-03 05:32

from django.db import migrations, models
import django.db.models.deletion
import our_team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_form', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=100)),
                ('linked_in_link', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_link', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.ImageField(upload_to=our_team.models.upload_to)),
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='our_team.designation')),
            ],
        ),
    ]
