# Generated by Django 4.1.7 on 2023-03-03 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('our_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='our_team.designation'),
        ),
    ]
