# Generated by Django 4.1.7 on 2023-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslider',
            name='sub_title',
            field=models.CharField(max_length=255),
        ),
    ]
