# Generated by Django 4.1.7 on 2023-03-03 09:04

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.ImageField(upload_to=service.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('catagories', models.ManyToManyField(to='service.category')),
                ('features', models.ManyToManyField(to='service.feature')),
                ('technologies', models.ManyToManyField(to='service.technology')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='feature',
            field=models.ManyToManyField(blank=True, null=True, to='service.feature'),
        ),
    ]
